---
date: 2017-01-30T20:05:05-08:00
title: Problem Sets
---

This page will list the Problem Sets and when they will be turned in throughout the course.  You can find a discussion about all of the Problem Sets [here](http://ismayc.github.io/soc301_s2017/ps-key/index.html).  Links to specific Problem Set discussions are below:

- Problem Set 2 (Due Thursday, February 9 by 4:20 PM)
    - Turn in on paper
    - Will be working to finish in class on Thursday in groups, but you should have a start on it BEFORE class
    - Learning Checks LC3.2-LC3.7, LC3.9-LC3.10 from [ModernDive](https://ismayc.github.io/moderndiver-book/3-tidy.html)
    - To run the R code given in the gray chunks in the textbook, you can use this "sandbox" I've created for you as the last chapter of the DataCamp course.  Click [here](https://campus.datacamp.com/courses/effective-data-storytelling-using-the-tidyverse/8864?ex=1).

***

- Problem Set 1 (Due Tuesday, February 7 by 4:20 PM)
    - Write down AT LEAST five multiple choice questions covering the **Introduction to R**
DataCamp course.  
    - Each question should have four possible answers.
    - Create a Google Doc with your questions and share with chester@pacificu.edu