---
title: "Schedule"
author: Chester Ismay
date: '2017-01-30T10:30:38-08:00'
subtitle: Pacific University - Spring 2017
---

The references to **Chapters**/**Sections** here correspond to the [**MODERN DIVE into Data with R**](http://moderndive.com) book.  Be sure to check the **DataCamp** link above for more details on the DataCamp (DC) assignments.  More details on the Problem Sets (PS) are available in the link above for Problem Sets.

```{r echo=FALSE, message=FALSE}
#options(servr.daemon = TRUE)
library(tidyverse)
library(knitr)
library(DT)
schedule <- read_csv("schedule.csv") %>%
  mutate(Date = paste(Month, Day)) %>%
  mutate(`DataCamp Due` = ifelse(material == "-" | grepl("Quiz", material) | is.na(material_link),
    material,
    paste0("<a href='", material_link, "'>", material, "</a>"))) %>% 
  mutate(`Problem Set Due` = ifelse(ps == "-" | is.na(ps) | is.na(ps_link),
    ps,
    paste0("<a href='", ps_link, "'>", ps, "</a>"))) %>% 
  select(Weekday, Date, `Content / Assessment`, `DataCamp Due`, `Problem Set Due`)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
if(knitr:::is_html_output()){
  schedule %>% datatable(rownames = FALSE,
                         class = 'cell-border stripe',
                         filter = list(position = 'top'),
                         options = list(pageLength = nrow(schedule), 
                                        autoWidth = TRUE,
                                        bInfo = FALSE,
                                        paging = FALSE),
                         escape = FALSE)
} else {
  knitr::kable(schedule, booktabs = TRUE, longtable = TRUE)
}
```