<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.18.1" />


<title>Problem Sets Discussion - SOC 301 - Spring 2017</title>
<meta property="og:title" content="Problem Sets Discussion - SOC 301 - Spring 2017">



  







<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/styles/github.min.css' rel='stylesheet' type='text/css'>

<link rel="stylesheet" href="../../css/main.css" media="all">





  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="../../" class="nav-logo">
    <img src="../../images/pacific.jpg" 
         width="50" 
         height="50" 
         alt="Logo">
  </a>
      
  <ul class="nav-links">
    
    <li><a href="../../datacamp/">DataCamp</a></li>
    
    <li><a href="../../problem-sets/">Problem Sets</a></li>
    
    <li><a href="../../resources/">Resources</a></li>
    
    <li><a href="../../schedule/">Schedule</a></li>
    
    <li><a href="../../syllabus/">Syllabus</a></li>
    
  </ul>
</nav>

      </header>

  
<main class="content" role="main">

  <article class="article">
    

    <h1 class="article-title">Problem Sets Discussion</h1>

    

    <div class="article-content">

<div id="TOC">
<ul>
<li><a href="#ps2-key">Problem Set 2</a></li>
<li><a href="#ps3-key">Problem Set 3</a></li>
<li><a href="#ps4-key">Problem Set 4</a></li>
<li><a href="#ps6-key">Problem Set 6</a></li>
<li><a href="#ps10-key">Problem Set 10</a></li>
<li><a href="#ps11-key">Problem Set 11</a></li>
</ul>
</div>

<hr />
<p>Page last updated at Tuesday, April 25, 2017 14:32:29 PDT</p>
<div id="ps2-key" class="section level1">
<h1>Problem Set 2</h1>
<p>Learning Checks LC3.2-LC3.7, LC3.9-LC3.10 from <a href="https://ismayc.github.io/moderndiver-book/3-tidy.html">ModernDive</a></p>
<div id="lc3.2" class="section level2">
<h2>LC3.2</h2>
<p>Say the following table are stock prices, how would you make this tidy?</p>
<table>
<thead>
<tr class="header">
<th align="left">time</th>
<th align="left">Boeing</th>
<th align="left">Amazon</th>
<th align="left">Google</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2009-01-01</td>
<td align="left">$173.55</td>
<td align="left">$174.90</td>
<td align="left">$174.34</td>
</tr>
<tr class="even">
<td align="left">2009-01-02</td>
<td align="left">$172.61</td>
<td align="left">$171.42</td>
<td align="left">$170.04</td>
</tr>
<tr class="odd">
<td align="left">2009-01-03</td>
<td align="left">$173.86</td>
<td align="left">$171.58</td>
<td align="left">$173.65</td>
</tr>
<tr class="even">
<td align="left">2009-01-04</td>
<td align="left">$170.77</td>
<td align="left">$173.89</td>
<td align="left">$174.87</td>
</tr>
<tr class="odd">
<td align="left">2009-01-05</td>
<td align="left">$174.29</td>
<td align="left">$170.16</td>
<td align="left">$172.19</td>
</tr>
</tbody>
</table>
<p><strong>Discussion</strong>: <code>Boeing</code>, <code>Amazon</code>, and <code>Google</code> are not variables by themselves, but rather levels of another variable <code>stock</code>. The numbers inside the table themselves are prices. Therefore, in its current form, <code>Google</code> corresponds both to the “name of a stock” and the “price of a stock” which violates the rules of tidy data. We can transform the data to make it <strong>tidy</strong>:</p>
<table>
<thead>
<tr class="header">
<th align="left">time</th>
<th align="center">stock</th>
<th align="right">price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2009-01-01</td>
<td align="center">Boeing</td>
<td align="right">$173.55</td>
</tr>
<tr class="even">
<td align="left">2009-01-02</td>
<td align="center">Boeing</td>
<td align="right">$172.61</td>
</tr>
<tr class="odd">
<td align="left">2009-01-03</td>
<td align="center">Boeing</td>
<td align="right">$173.86</td>
</tr>
<tr class="even">
<td align="left">2009-01-04</td>
<td align="center">Boeing</td>
<td align="right">$170.77</td>
</tr>
<tr class="odd">
<td align="left">2009-01-05</td>
<td align="center">Boeing</td>
<td align="right">$174.29</td>
</tr>
<tr class="even">
<td align="left">2009-01-01</td>
<td align="center">Amazon</td>
<td align="right">$174.90</td>
</tr>
<tr class="odd">
<td align="left">2009-01-02</td>
<td align="center">Amazon</td>
<td align="right">$171.42</td>
</tr>
<tr class="even">
<td align="left">2009-01-03</td>
<td align="center">Amazon</td>
<td align="right">$171.58</td>
</tr>
<tr class="odd">
<td align="left">2009-01-04</td>
<td align="center">Amazon</td>
<td align="right">$173.89</td>
</tr>
<tr class="even">
<td align="left">2009-01-05</td>
<td align="center">Amazon</td>
<td align="right">$170.16</td>
</tr>
<tr class="odd">
<td align="left">2009-01-01</td>
<td align="center">Google</td>
<td align="right">$174.34</td>
</tr>
<tr class="even">
<td align="left">2009-01-02</td>
<td align="center">Google</td>
<td align="right">$170.04</td>
</tr>
<tr class="odd">
<td align="left">2009-01-03</td>
<td align="center">Google</td>
<td align="right">$173.65</td>
</tr>
<tr class="even">
<td align="left">2009-01-04</td>
<td align="center">Google</td>
<td align="right">$174.87</td>
</tr>
<tr class="odd">
<td align="left">2009-01-05</td>
<td align="center">Google</td>
<td align="right">$172.19</td>
</tr>
</tbody>
</table>
</div>
<div id="lc3.3" class="section level2">
<h2>LC3.3</h2>
<p>What does any <em>ONE</em> row in this <code>flights</code> dataset refer to?</p>
<ul>
<li>A. Data on an airline</li>
<li>B. Data on a flight</li>
<li>C. Data on an airport</li>
<li>D. Data on multiple flights</li>
</ul>
<p><strong>Discussion</strong>: The correct answer is B here. The observational unit is flight. All of the variables are measurements/characteristics of a given flight. Each row is an observation of one flight containing data about that flight.</p>
</div>
<div id="lc3.4" class="section level2">
<h2>LC3.4</h2>
<p>What are some examples in this dataset of <strong>categorical</strong> variables? What makes them different than <strong>quantitative</strong> variables?</p>
<p><strong>Discussion</strong>: The <strong>categorical</strong> variables are <code>carrier</code>, <code>tailnum</code>, <code>origin</code>, and <code>dest</code>. The <strong>quantitative</strong> variables are all of the <code>&lt;int</code>&gt; and <code>&lt;dbl&gt;</code> class variables: <code>year</code>, <code>month</code>, <code>day</code>, <code>dep_time</code>, <code>sched_dep_time</code>, <code>arr_time</code>, <code>sched_arr_time</code>, <code>arr_delay</code>, <code>flight</code>, <code>air_time</code>, <code>distance</code>, <code>hour</code>, and <code>minute</code>. Note that <code>time_hour</code> is labeled as <code>&lt;dttm&gt;</code> corresponding to date-time. This is a special format in R for handling the oddities of dates and times. Note also that <code>dep_time</code> and other similar variables are not labeled as <code>&lt;dttm&gt;</code>, but rather as a number. Think about what problems this might cause in your analyses.</p>
</div>
<div id="lc3.5" class="section level2">
<h2>LC3.5</h2>
<p>What does <code>int</code>, <code>dbl</code>, and <code>chr</code> mean in the output above? If you need a hint, you might want to run <code>str(flights)</code> instead.</p>
<p><strong>Discussion</strong>: These correspond to the <code>class</code> of each variable in R. <code>dbl</code> is the same thing as <code>num</code> and represents numbers with decimal values. <code>int</code> corresponds to integers (whole numbers and their negative opposites (-5, 4, 79, 0, 12342, etc.)). <code>chr</code> corresponds to character values/strings and these are almost always categorical variables. The output of the similar <code>str(flights)</code> is below.</p>
<pre class="r"><code>library(nycflights13)
str(flights)</code></pre>
<pre><code>## Classes &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;:    336776 obs. of  19 variables:
##  $ year          : int  2013 2013 2013 2013 2013 2013 2013 2013 2013 2013 ...
##  $ month         : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ day           : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ dep_time      : int  517 533 542 544 554 554 555 557 557 558 ...
##  $ sched_dep_time: int  515 529 540 545 600 558 600 600 600 600 ...
##  $ dep_delay     : num  2 4 2 -1 -6 -4 -5 -3 -3 -2 ...
##  $ arr_time      : int  830 850 923 1004 812 740 913 709 838 753 ...
##  $ sched_arr_time: int  819 830 850 1022 837 728 854 723 846 745 ...
##  $ arr_delay     : num  11 20 33 -18 -25 12 19 -14 -8 8 ...
##  $ carrier       : chr  &quot;UA&quot; &quot;UA&quot; &quot;AA&quot; &quot;B6&quot; ...
##  $ flight        : int  1545 1714 1141 725 461 1696 507 5708 79 301 ...
##  $ tailnum       : chr  &quot;N14228&quot; &quot;N24211&quot; &quot;N619AA&quot; &quot;N804JB&quot; ...
##  $ origin        : chr  &quot;EWR&quot; &quot;LGA&quot; &quot;JFK&quot; &quot;JFK&quot; ...
##  $ dest          : chr  &quot;IAH&quot; &quot;IAH&quot; &quot;MIA&quot; &quot;BQN&quot; ...
##  $ air_time      : num  227 227 160 183 116 150 158 53 140 138 ...
##  $ distance      : num  1400 1416 1089 1576 762 ...
##  $ hour          : num  5 5 5 5 6 5 6 6 6 6 ...
##  $ minute        : num  15 29 40 45 0 58 0 0 0 0 ...
##  $ time_hour     : POSIXct, format: &quot;2013-01-01 05:00:00&quot; &quot;2013-01-01 05:00:00&quot; ...</code></pre>
</div>
<div id="lc3.6" class="section level2">
<h2>LC3.6</h2>
<p>How many different columns are in this dataset?</p>
<p><strong>Discussion</strong>:</p>
<pre class="r"><code>library(nycflights13)
glimpse(flights)</code></pre>
<pre><code>## Observations: 336,776
## Variables: 19
## $ year           &lt;int&gt; 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013,...
## $ month          &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
## $ day            &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
## $ dep_time       &lt;int&gt; 517, 533, 542, 544, 554, 554, 555, 557, 557, 55...
## $ sched_dep_time &lt;int&gt; 515, 529, 540, 545, 600, 558, 600, 600, 600, 60...
## $ dep_delay      &lt;dbl&gt; 2, 4, 2, -1, -6, -4, -5, -3, -3, -2, -2, -2, -2...
## $ arr_time       &lt;int&gt; 830, 850, 923, 1004, 812, 740, 913, 709, 838, 7...
## $ sched_arr_time &lt;int&gt; 819, 830, 850, 1022, 837, 728, 854, 723, 846, 7...
## $ arr_delay      &lt;dbl&gt; 11, 20, 33, -18, -25, 12, 19, -14, -8, 8, -2, -...
## $ carrier        &lt;chr&gt; &quot;UA&quot;, &quot;UA&quot;, &quot;AA&quot;, &quot;B6&quot;, &quot;DL&quot;, &quot;UA&quot;, &quot;B6&quot;, &quot;EV&quot;,...
## $ flight         &lt;int&gt; 1545, 1714, 1141, 725, 461, 1696, 507, 5708, 79...
## $ tailnum        &lt;chr&gt; &quot;N14228&quot;, &quot;N24211&quot;, &quot;N619AA&quot;, &quot;N804JB&quot;, &quot;N668DN...
## $ origin         &lt;chr&gt; &quot;EWR&quot;, &quot;LGA&quot;, &quot;JFK&quot;, &quot;JFK&quot;, &quot;LGA&quot;, &quot;EWR&quot;, &quot;EWR&quot;...
## $ dest           &lt;chr&gt; &quot;IAH&quot;, &quot;IAH&quot;, &quot;MIA&quot;, &quot;BQN&quot;, &quot;ATL&quot;, &quot;ORD&quot;, &quot;FLL&quot;...
## $ air_time       &lt;dbl&gt; 227, 227, 160, 183, 116, 150, 158, 53, 140, 138...
## $ distance       &lt;dbl&gt; 1400, 1416, 1089, 1576, 762, 719, 1065, 229, 94...
## $ hour           &lt;dbl&gt; 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5,...
## $ minute         &lt;dbl&gt; 15, 29, 40, 45, 0, 58, 0, 0, 0, 0, 0, 0, 0, 0, ...
## $ time_hour      &lt;dttm&gt; 2013-01-01 05:00:00, 2013-01-01 05:00:00, 2013...</code></pre>
<p>We see above from running <code>glimpse(flights)</code> that the number of variables is 19. In a tidy data frame such as <code>flights</code>, the number of columns corresponds directly to the number of variables so the number of columns is 19. This can also be obtained using the <code>ncol</code> function via <code>ncol(flights)</code>.</p>
</div>
<div id="lc3.7" class="section level2">
<h2>LC3.7</h2>
<p>How many different rows are in this dataset?</p>
<p><strong>Discussion</strong>:</p>
<p>We see above from running <code>glimpse(flights)</code> that the number of observations is 336,776. In a tidy data frame such as <code>flights</code>, the number of rows corresponds directly to the number of observations/cases so the number of rows is also 336,776. This can also be obtained using the <code>nrow</code> function via <code>nrow(flights)</code>.</p>
</div>
<div id="lc3.9" class="section level2">
<h2>LC3.9</h2>
<p>What properties of the observational unit do each of <code>lat</code>, <code>lon</code>, <code>alt</code>, <code>tz</code>, <code>dst</code>, and <code>tzone</code> describe for the <code>airports</code> data frame? Note that you may want to use <code>?airports</code> to get more information or go to the reference manual for the <code>nycflights13</code> package <a href="https://cran.r-project.org/web/packages/nycflights13/nycflights13.pdf">here</a>.</p>
<p><strong>Discussion</strong>:</p>
<p>Using <code>?airports</code>, we see that <code>lat</code> and <code>lon</code> correspond to the latitude and longitude of the location of the airport. <code>alt</code> is the altitude of the airport in feet. <code>tz</code> is the offset of the airport’s time zone from Greenwich Mean Time. <code>dst</code> corresponds to “Daylight savings time zone” with values of <code>&quot;A&quot;</code> for US DST, <code>&quot;U&quot;</code> for unknown, and <code>&quot;N&quot;</code> for no DST. Lastly, <code>tzone</code> is the name of the time zone in which the airport is located.</p>
</div>
<div id="lc3.10" class="section level2">
<h2>LC3.10</h2>
<p>Provide the names of variables in a data frame with at least three variables in which one of them is an identification variable and the other two are not.</p>
<p><strong>Discussion</strong>: Many answers are appropriate here. The identification variable should correspond to the observational unit of the data frame. Here is one example:</p>
<table>
<thead>
<tr class="header">
<th>Student ID</th>
<th>Major</th>
<th align="center">Percentage</th>
<th>Grade</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1000</td>
<td>Sociology</td>
<td align="center">95</td>
<td>A</td>
</tr>
<tr class="even">
<td>1001</td>
<td>Biology</td>
<td align="center">50</td>
<td>F</td>
</tr>
<tr class="odd">
<td>1002</td>
<td>History</td>
<td align="center">76</td>
<td>C</td>
</tr>
</tbody>
</table>
<hr />
</div>
</div>
<div id="ps3-key" class="section level1">
<h1>Problem Set 3</h1>
<p>Learning Checks <a href="https://ismayc.github.io/moderndiver-book/3-tidy.html">LC3.11-LC3.13 and LC3.15</a> AND <a href="https://ismayc.github.io/moderndiver-book/4-viz.html">LC4.1-LC4.2, LC4.4, LC4.6-LC4.7, and LC4.10-LC4.13</a></p>
<div id="lc3.11" class="section level2">
<h2>LC3.11</h2>
<p>What are common characteristics of “tidy” datasets?</p>
<p><strong>Discussion</strong>: Tidy data sets tend to be in a narrow, long format since they list all possible values of each combination of the different variables. They have one observation per row, one variable per column, one observational unit per data frame, and the entries on the inside of the table are values, each representing the intersection of a particular observation and a particular variable.</p>
</div>
<div id="lc3.12" class="section level2">
<h2>LC3.12</h2>
<p>What makes “tidy” datasets useful for organizing data?</p>
<p><strong>Discussion</strong>: They allow you to easily summarize data across a variable or to plot data and show different relationships across other variables. They are incredibly useful in looking for multivariate relationships (more than two variables) in data. You’ll see more of this as the semester goes along.</p>
</div>
<div id="lc3.13" class="section level2">
<h2>LC3.13</h2>
<p>How many variables are presented in the table below? What does each row correspond to? (<strong>Hint:</strong> You may not be able to answer both of these questions immediately but take your best guess.)</p>
<table>
<thead>
<tr class="header">
<th align="right">students</th>
<th align="right">faculty</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">4</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">3</td>
</tr>
</tbody>
</table>
<p><strong>Discussion</strong>: This is an incredibly difficult problem to figure out. You can guess that <code>students</code> and <code>faculty</code> should actually be levels of a variable called something like <code>type</code> or <code>role</code>. The numbers inside the table represent counts of some sort, so there may be at least two other variables floating around in there.</p>
</div>
<div id="lc3.15" class="section level2">
<h2>LC3.15</h2>
<p>The actual data presented in LC3.13 is given below in tidy data format:</p>
<table>
<thead>
<tr class="header">
<th align="left">role</th>
<th align="center">Sociology?</th>
<th align="left">Type of School</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">student</td>
<td align="center">TRUE</td>
<td align="left">Public</td>
</tr>
<tr class="even">
<td align="left">student</td>
<td align="center">TRUE</td>
<td align="left">Public</td>
</tr>
<tr class="odd">
<td align="left">student</td>
<td align="center">TRUE</td>
<td align="left">Public</td>
</tr>
<tr class="even">
<td align="left">student</td>
<td align="center">TRUE</td>
<td align="left">Public</td>
</tr>
<tr class="odd">
<td align="left">student</td>
<td align="center">FALSE</td>
<td align="left">Public</td>
</tr>
<tr class="even">
<td align="left">student</td>
<td align="center">FALSE</td>
<td align="left">Public</td>
</tr>
<tr class="odd">
<td align="left">student</td>
<td align="center">FALSE</td>
<td align="left">Private</td>
</tr>
<tr class="even">
<td align="left">student</td>
<td align="center">FALSE</td>
<td align="left">Private</td>
</tr>
<tr class="odd">
<td align="left">student</td>
<td align="center">FALSE</td>
<td align="left">Private</td>
</tr>
<tr class="even">
<td align="left">student</td>
<td align="center">FALSE</td>
<td align="left">Private</td>
</tr>
<tr class="odd">
<td align="left">faculty</td>
<td align="center">TRUE</td>
<td align="left">Public</td>
</tr>
<tr class="even">
<td align="left">faculty</td>
<td align="center">TRUE</td>
<td align="left">Public</td>
</tr>
<tr class="odd">
<td align="left">faculty</td>
<td align="center">FALSE</td>
<td align="left">Public</td>
</tr>
<tr class="even">
<td align="left">faculty</td>
<td align="center">FALSE</td>
<td align="left">Private</td>
</tr>
<tr class="odd">
<td align="left">faculty</td>
<td align="center">FALSE</td>
<td align="left">Private</td>
</tr>
</tbody>
</table>
<ul>
<li>What does each row correspond to?<br />
</li>
<li>What are the different variables in this data frame?<br />
</li>
<li>The <code>Sociology?</code> variable is known as a logical variable. What types of values does a logical variable take on?</li>
</ul>
<p><strong>Discussion</strong>:</p>
<ul>
<li>Each row corresponds to a particular observation (an instance of the observational unit). In this case, each row corresponds to a particular person, either a faculty member or a student.</li>
<li>The different variables are <code>role</code>, <code>Sociology?</code>, and <code>Type of School</code>.</li>
<li>Logical variables take on the values of <code>TRUE</code> or <code>FALSE</code>.</li>
</ul>
</div>
<div id="lc4.1" class="section level2">
<h2>LC4.1</h2>
<p>Take a look at both the <code>flights</code> and <code>all_alaska_flights</code> data frames by running <code>View(flights)</code> and <code>View(all_alaska_flights)</code> in the console. In what respect do these data frames differ?</p>
<p><strong>Discussion</strong>: Recall that you don’t have the ability to run <code>View</code> in DataCamp and we aren’t using RStudio just yet. You can find interactive versions of both data frames <a href="https://ismayc.github.io/Effective-Data-Storytelling-using-the-tidyverse/moderndive.html">here</a> though.</p>
<p>The only difference between these data frames is that <code>flights</code> contains information about 2013 NYC flights from all carriers and <code>all_alaska_flights</code> only contains information about flights using Alaskan Airlines.</p>
</div>
<div id="lc4.2" class="section level2">
<h2>LC4.2</h2>
<p>What are some practical reasons why <code>dep_delay</code> and <code>arr_delay</code> have a positive relationship?</p>
<p><strong>Discussion</strong>:</p>
<p>Flights that are late in leaving the origin airport will almost surely be late in arriving at the destination airport. Further, a flight that is delayed 15 minutes on departure will probably be delayed around 15 minutes on arrival. Pilots are able to make up some time in the air sometimes, but a positive relationship is clear here. As <code>dep_delay</code> increases, <code>arr_delay</code> also increases.</p>
<div id="section" class="section level3">
<h3></h3>
</div>
</div>
<div id="lc4.6" class="section level2">
<h2>LC4.6</h2>
<p>Create a new scatter-plot using different variables in the <code>all_alaska_flights</code> data frame by modifying the example above. (Run your code in the sandbox in DataCamp and then write your code on your paper. Discuss what findings you have when looking at the plot. Remember that scatter-plots only work when analyzing the relationship between two <strong>numerical</strong> variables!)</p>
<p><strong>Discussion</strong>:</p>
<p>There are many potential plots you could create here. Here is one example:</p>
<pre class="r"><code>library(nycflights13)
library(ggplot2)
all_alaska_flights &lt;- flights %&gt;% filter(carrier == &quot;AS&quot;)
ggplot(data = all_alaska_flights, mapping = aes(x = air_time, y = distance)) +
  geom_point()</code></pre>
<p><img src="figures/unnamed-chunk-8-1.png" width="672" /></p>
<p>This might initially look like an error but Alaskan Airlines online flies to Seattle from New York City. Therefore, all of the <code>distance</code> values are 2402. We can see that there was quite a bit of variability in terms of <code>air_time</code> though.</p>
<!-- -->
</div>
<div id="lc4.7" class="section level2">
<h2>LC4.7</h2>
<p>Why is setting the <code>alpha</code> argument value useful with scatter-plots? What further information does it give you that a regular scatter-plot cannot?</p>
<p><strong>Discussion</strong>:</p>
<p>The <code>alpha</code> argument allows for the setting of the transparency of the points. This allows you to see when many points are over-lapping and to identify over-plotting in your scatter-plot.</p>
</div>
<div id="lc4.10" class="section level2">
<h2>LC4.10</h2>
<p>The weather data is recorded hourly. Why does the <code>time_hour</code> variable correctly identify the hour of the measurement whereas the <code>hour</code> variable does not?</p>
<p><strong>Discussion</strong>:</p>
<p>The <code>time_hour</code> variable gives the precise hour on a given day. The <code>hour</code> variable is just an integer value from 0 to 23 so without other information, <code>hour</code> only gives the hour of a particular day.</p>
</div>
<div id="lc4.11" class="section level2">
<h2>LC4.11</h2>
<p>Why should line-graphs be avoided when there is not a clear ordering of the horizontal axis?</p>
<p><strong>Discussion</strong>:</p>
<p>Line-graphs only show trends in the data and are best used with time as the explanatory variable on the horizontal axis. When there is no clear ordering of the horizontal axis, one could deceive the reader into thinking a pattern/trend exists when, in fact, one does not.</p>
</div>
<div id="lc4.12" class="section level2">
<h2>LC4.12</h2>
<p>Why are line-graphs frequently used when time is the explanatory variable?</p>
<p><strong>Discussion</strong>:</p>
<p>Time on the horizontal axis and a single value for each time point provides a simple way to identify a trend in the variable. It allows for one to easily answer questions such as “Is the response variable increasing over time?”, “Where are there peaks and valleys in the response variable?”, etc.</p>
</div>
<div id="lc4.13" class="section level2">
<h2>LC4.13</h2>
<p>Plot a time series of a variable other than <code>temp</code> for Newark Airport in the first 15 days of January 2013. (Run your code in the sandbox in DataCamp and then write your code on your paper. Discuss what findings you have when looking at the plot. Remember that scatter-plots only work when analyzing the relationship between two <strong>numerical</strong> variables!)</p>
<p><strong>Discussion</strong>:</p>
<p>There are many potential answers for this question. Here is one answer:</p>
<pre class="r"><code>library(nycflights13)
library(ggplot2)
early_january_weather &lt;- weather %&gt;% 
  filter(origin == &quot;EWR&quot; &amp; month == 1 &amp; day &lt;= 15)
ggplot(data = early_january_weather, mapping = aes(x = time_hour, y = wind_gust)) +
  geom_line()</code></pre>
<p><img src="figures/unnamed-chunk-9-1.png" width="672" /></p>
<p>What immediately stands out in this plot are the days with no wind gusts at all and values of 0. There appears to be only one wind gust over 25 mpg around January 2nd or 3rd.</p>
<hr />
</div>
</div>
<div id="ps4-key" class="section level1">
<h1>Problem Set 4</h1>
<p>Learning Checks <a href="https://ismayc.github.io/moderndiver-book/4-viz.html">LC4.14, LC4.16, LC4.18, LC4.19, LC4.21-LC4.28, LC4.30, LC4.33-LC4.34, LC4.36-LC4.37</a></p>
<div id="lc4.14" class="section level2">
<h2>LC4.14</h2>
<p>What does changing the number of bins from 30 to 60 tell us about the distribution of temperatures?</p>
<p><strong>Discussion</strong>:</p>
<p>Increasing the number of bins allows for us to see the distribution of temperatures in finer detail.</p>
</div>
<div id="lc4.16" class="section level2">
<h2>LC4.16</h2>
<p>What would you guess is the “center” value in this distribution? Why did you make that choice?</p>
<p><strong>Discussion</strong>:</p>
<p>There is no exact answer here at this point in the course. I wanted you to think about what the balancing point would be having half the values before it and half after it. This falls somewhere between 50 and 55.</p>
</div>
<div id="lc4.18" class="section level2">
<h2>LC4.18</h2>
<p>What other things do you notice about the faceted plot above? How does a faceted plot help us see relationships between two variables?</p>
<p><strong>Discussion</strong>:</p>
<p>The faceted plot allows us to better see the range of temperatures for each month. In general, a faceted plot can be helpful in seeing trends in one variable compared to another.</p>
</div>
<div id="lc4.19" class="section level2">
<h2>LC4.19</h2>
<p>What do the numbers 1-12 correspond to in the plot above? What about 25, 50, 75, 100?</p>
<p><strong>Discussion</strong>:</p>
<p>The numbers 1-12 correspond to months in the year 2013. The nubmers 25, 50, 75, and 100 correspond to Fahrenheit temperatures.</p>
</div>
<div id="lc4.21" class="section level2">
<h2>LC4.21</h2>
<p>Does the <code>temp</code> variable in the <code>weather</code> data set have a lot of variability? Why do you say that?</p>
<p><strong>Discussion</strong>:</p>
<p>New York City does have a broad range of temperatures throughout the year. We see that summer months tend to be much warmer than winter months, so, yes, <code>temp</code> in <code>weather</code> does have a lot of variability.</p>
</div>
<div id="lc4.22" class="section level2">
<h2>LC4.22</h2>
<p>What does the dot at the bottom of the plot for May correspond to? Explain what might have occurred in May to produce this point.</p>
<p><strong>Discussion</strong>:</p>
<p>The dot at the bottom of the plot for May corresponds to a low outlier. This could have been a very cold hour, but since no other hours have that cold of a temperature it is more than likely a measurement error.</p>
</div>
<div id="lc4.23" class="section level2">
<h2>LC4.23</h2>
<p>Which months have the highest variability in temperature? What reasons do you think this is?</p>
<p><strong>Discussion</strong>:</p>
<p>The spring and fall months have the highest variability in temperature. These months tend to have cold mornings and warmer high temperatures.</p>
</div>
<div id="lc4.24" class="section level2">
<h2>LC4.24</h2>
<p>We looked at the distribution of a continuous variable over a categorical variable here with this boxplot. Why can’t we look at the distribution of one continuous variable over the distribution of another continuous variable? Say, temperature across pressure, for example?</p>
<p><strong>Discussion</strong>:</p>
<p>A boxplot works well because you can look at the distribution of the continuous variable across the different (often only a few) levels of the categorical variable. A continuous explanatory variable will have many, many levels making the boxplot very hard to read and interpret.</p>
</div>
<div id="lc4.25" class="section level2">
<h2>LC4.25</h2>
<p>Boxplots provide a simple way to identify outliers. Why may outliers be easier to identify when looking at a boxplot instead of a faceted histogram?</p>
<p><strong>Discussion</strong>:</p>
<p>A faceted histogram shows the height of the bin and if outliers are all alone they will appear as having a bin of height close to zero, which is almost indistinguishable from zero. Therefore, they are more likely to be missed when looking at a faceted histogram. A boxplot will clearly show them.</p>
</div>
<div id="lc4.26" class="section level2">
<h2>LC4.26</h2>
<p>Why are histograms inappropriate for visualizing categorical variables?</p>
<p><strong>Discussion</strong>:</p>
<p>Histograms show how many values fall into different bins of a numerical variable that falls on a continuum. (This is one reason why the bins are touching.) Since a categorical variable does not fall on a continuum, histograms are inappropriate.</p>
</div>
<div id="lc4.27" class="section level2">
<h2>LC4.27</h2>
<p>What is the difference between histograms and barplots?</p>
<p><strong>Discussion</strong>:</p>
<p>The bins touch on a histogram and the bars/bins on a barplot do not. Histograms show the distribution of a continuous variable whereas barplots show the distribution of a categorical variable.</p>
</div>
<div id="lc4.28" class="section level2">
<h2>LC4.28</h2>
<p>How many Envoy Air flights departed NYC in 2013?</p>
<p><strong>Discussion</strong>:</p>
<p>Since Envoy Air corresponds to <code>carrier</code> code <code>MQ</code> via the <code>airports</code> data frame, we see that 26,397 flights departed New York City in 2013.</p>
</div>
<div id="lc4.30" class="section level2">
<h2>LC4.30</h2>
<p>Why should pie charts be avoided and replaced by barplots?</p>
<p><strong>Discussion</strong>:</p>
<p>Pie charts rely on us being able to tell the different between different slices of the pie in terms of the percentage of area covered. Our eyes and brains are not naturally good at this task. We are extremely good at determining the height of bars and comparing them across different groups as a barplot shows.</p>
</div>
<div id="lc4.33" class="section level2">
<h2>LC4.33</h2>
<p>What can you say, if anything, about the relationship between airline and airport in NYC in 2013 in regards to the number of departing flights?</p>
<p><strong>Discussion</strong>:</p>
<p>Certain airlines tend to depart from one airport far more than the other two airports. For example, ExpressJet Airlines has nearly all of its flights from Newark.</p>
</div>
<div id="lc4.34" class="section level2">
<h2>LC4.34</h2>
<p>Why might the side-by-side barplot be preferable to a stacked barplot in this case?</p>
<p><strong>Discussion</strong>:</p>
<p>It is harder to compare the frequency of flights for LaGuardia or JFK when looking at a stacked barplot since they are already stacked on top of Newark.</p>
</div>
<div id="lc4.36" class="section level2">
<h2>LC4.36</h2>
<p>Why is the faceted barplot preferred to the side-by-side and stacked barplots in this case?</p>
<p><strong>Discussion</strong>:</p>
<p>A faceted barplot allows for comparisons to be made more easily across both airports AND airlines.</p>
</div>
<div id="lc4.37" class="section level2">
<h2>LC4.37</h2>
<p>What information about the different carriers at different airports is more easily seen in the faceted barplot?</p>
<p><strong>Discussion</strong>:</p>
<p>The faceted barplot provides an easier way to see the airlines that have no departing flights and also many flights from each airport.</p>
<hr />
</div>
</div>
<div id="ps6-key" class="section level1">
<h1>Problem Set 6</h1>
<p>Learning Checks <a href="https://ismayc.github.io/moderndiver-book/5-manip.html">LC5.1-LC5.2, LC5.4-LC5.5, LC5.7, LC5.9-LC5.14</a></p>
<div id="lc5.1" class="section level2">
<h2>LC5.1</h2>
<p>What’s another way using <code>!</code> we could filter only the rows that are not going to Burlington, VT nor Seattle, WA in the <code>flights</code> data frame? Test this out using the code above.</p>
<p><strong>Discussion</strong>:</p>
<p>This question refers to</p>
<pre class="r"><code>library(dplyr)
library(nycflights13)
not_BTV_SEA &lt;- flights %&gt;% 
  filter(!(dest == &quot;BTV&quot; | dest == &quot;SEA&quot;))</code></pre>
<p>in choosing only the rows of flights that don’t go to Burlington, Vermont or Seattle, Washington. Another way to do this is to choose those that don’t go to Burlington AND those that don’t go to Seattle:</p>
<pre class="r"><code>not_BTV_SEA2 &lt;- flights %&gt;% 
  filter(!(dest == &quot;BTV&quot;), !(dest == &quot;SEA&quot;))</code></pre>
<p>We can use the <code>identical</code> function to show that these objects are the same:</p>
<pre class="r"><code>identical(not_BTV_SEA, not_BTV_SEA2)</code></pre>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="lc5.2" class="section level2">
<h2>LC5.2</h2>
<p>Say a doctor is studying the effect of smoking on lung cancer of a large number of patients who have records measured at five year intervals. He notices that a large number of patients have missing data points because the patient has died, so he chooses to ignore these patients in his analysis. What is wrong with this doctor’s approach?</p>
<p><strong>Discussion</strong>:</p>
<p>By ignoring these data points, he is creating bias in the data. One of the major things the study is probably trying to determine is the role of smoking on lung cancer and whether or not patients had died. The point of this exercise is to understand that just applying <code>na.rm = TRUE</code> into your analysis to remove missing values and warnings should only be done with caution.</p>
</div>
<div id="lc5.4" class="section level2">
<h2>LC5.4</h2>
<p>Why doesn’t the following code work? You may want to run the code line by line instead of all at once. In other words, run <code>summary_temp &lt;- weather %&gt;% summarize(mean = mean(temp, na.rm = TRUE))</code> first.</p>
<pre class="r"><code>summary_temp &lt;- weather %&gt;%   
  summarize(mean = mean(temp, na.rm = TRUE)) %&gt;% 
  summarize(std_dev = sd(temp, na.rm = TRUE))</code></pre>
<p><strong>Discussion</strong>:</p>
<p>The data frame created via <code>summary_temp &lt;- weather %&gt;% summarize(mean = mean(temp, na.rm = TRUE))</code> will only contain one column with one value corresponding to the overall mean temperature. Thus, we can’t also calculate the standard deviation of <code>temp</code> since <code>temp</code> no longer exists in this aggregated data frame. The correct code to calculate the mean and standard deviation is</p>
<pre class="r"><code>summary_temp &lt;- weather %&gt;%   
  summarize(mean = mean(temp, na.rm = TRUE),
            std_dev = sd(temp, na.rm = TRUE))
summary_temp</code></pre>
<pre><code>## # A tibble: 1 × 2
##       mean  std_dev
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1 55.20351 17.78212</code></pre>
</div>
<div id="lc5.5" class="section level2">
<h2>LC5.5</h2>
<p>Recall from Chapter <a href="https://ismayc.github.io/moderndiver-book/4-viz.html">4</a> when we looked at plots of temperatures by months in NYC. What does the standard deviation column in the <code>summary_monthly_temp</code> data frame tell us about temperatures in New York City throughout the year?</p>
<p><strong>Discussion</strong>:</p>
<p>This is referencing</p>
<pre class="r"><code>library(knitr) # for kable function
summary_monthly_temp &lt;- weather %&gt;% 
  group_by(month) %&gt;% 
  summarize(mean = mean(temp, na.rm = TRUE), 
            std_dev = sd(temp, na.rm = TRUE))
kable(summary_monthly_temp)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">month</th>
<th align="right">mean</th>
<th align="right">std_dev</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">35.64127</td>
<td align="right">10.185459</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">34.15454</td>
<td align="right">6.940228</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">39.81404</td>
<td align="right">6.224948</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">51.67094</td>
<td align="right">8.785250</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">61.59185</td>
<td align="right">9.608687</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">72.14500</td>
<td align="right">7.603357</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">80.00967</td>
<td align="right">7.147631</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">74.40495</td>
<td align="right">5.171365</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">67.42582</td>
<td align="right">8.475824</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">60.03305</td>
<td align="right">8.829652</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="right">45.10893</td>
<td align="right">10.502249</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="right">38.36811</td>
<td align="right">9.940822</td>
</tr>
</tbody>
</table>
<p>We can see that the variability in temperature is highest in January and November since the standard deviation is highest in those months. June, July, and August have the lowest variability followed by February and March. This corresponds to temperature being roughly the same value all throughout those months whereas there is a lot of variability in the temperature in January and November.</p>
</div>
<div id="lc5.7" class="section level2">
<h2>LC5.7</h2>
<p>Recreate <code>by_monthly_origin</code>, but instead of grouping via <code>group_by(origin, month)</code>, group variables in a different order <code>group_by(month, origin)</code>. What differs in the resulting data set?</p>
<p><strong>Discussion</strong>:</p>
<p>This is referencing</p>
<pre class="r"><code>by_monthly_origin &lt;- flights %&gt;% 
  group_by(origin, month) %&gt;% 
  summarize(count = n())
kable(by_monthly_origin)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">origin</th>
<th align="right">month</th>
<th align="right">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">EWR</td>
<td align="right">1</td>
<td align="right">9893</td>
</tr>
<tr class="even">
<td align="left">EWR</td>
<td align="right">2</td>
<td align="right">9107</td>
</tr>
<tr class="odd">
<td align="left">EWR</td>
<td align="right">3</td>
<td align="right">10420</td>
</tr>
<tr class="even">
<td align="left">EWR</td>
<td align="right">4</td>
<td align="right">10531</td>
</tr>
<tr class="odd">
<td align="left">EWR</td>
<td align="right">5</td>
<td align="right">10592</td>
</tr>
<tr class="even">
<td align="left">EWR</td>
<td align="right">6</td>
<td align="right">10175</td>
</tr>
<tr class="odd">
<td align="left">EWR</td>
<td align="right">7</td>
<td align="right">10475</td>
</tr>
<tr class="even">
<td align="left">EWR</td>
<td align="right">8</td>
<td align="right">10359</td>
</tr>
<tr class="odd">
<td align="left">EWR</td>
<td align="right">9</td>
<td align="right">9550</td>
</tr>
<tr class="even">
<td align="left">EWR</td>
<td align="right">10</td>
<td align="right">10104</td>
</tr>
<tr class="odd">
<td align="left">EWR</td>
<td align="right">11</td>
<td align="right">9707</td>
</tr>
<tr class="even">
<td align="left">EWR</td>
<td align="right">12</td>
<td align="right">9922</td>
</tr>
<tr class="odd">
<td align="left">JFK</td>
<td align="right">1</td>
<td align="right">9161</td>
</tr>
<tr class="even">
<td align="left">JFK</td>
<td align="right">2</td>
<td align="right">8421</td>
</tr>
<tr class="odd">
<td align="left">JFK</td>
<td align="right">3</td>
<td align="right">9697</td>
</tr>
<tr class="even">
<td align="left">JFK</td>
<td align="right">4</td>
<td align="right">9218</td>
</tr>
<tr class="odd">
<td align="left">JFK</td>
<td align="right">5</td>
<td align="right">9397</td>
</tr>
<tr class="even">
<td align="left">JFK</td>
<td align="right">6</td>
<td align="right">9472</td>
</tr>
<tr class="odd">
<td align="left">JFK</td>
<td align="right">7</td>
<td align="right">10023</td>
</tr>
<tr class="even">
<td align="left">JFK</td>
<td align="right">8</td>
<td align="right">9983</td>
</tr>
<tr class="odd">
<td align="left">JFK</td>
<td align="right">9</td>
<td align="right">8908</td>
</tr>
<tr class="even">
<td align="left">JFK</td>
<td align="right">10</td>
<td align="right">9143</td>
</tr>
<tr class="odd">
<td align="left">JFK</td>
<td align="right">11</td>
<td align="right">8710</td>
</tr>
<tr class="even">
<td align="left">JFK</td>
<td align="right">12</td>
<td align="right">9146</td>
</tr>
<tr class="odd">
<td align="left">LGA</td>
<td align="right">1</td>
<td align="right">7950</td>
</tr>
<tr class="even">
<td align="left">LGA</td>
<td align="right">2</td>
<td align="right">7423</td>
</tr>
<tr class="odd">
<td align="left">LGA</td>
<td align="right">3</td>
<td align="right">8717</td>
</tr>
<tr class="even">
<td align="left">LGA</td>
<td align="right">4</td>
<td align="right">8581</td>
</tr>
<tr class="odd">
<td align="left">LGA</td>
<td align="right">5</td>
<td align="right">8807</td>
</tr>
<tr class="even">
<td align="left">LGA</td>
<td align="right">6</td>
<td align="right">8596</td>
</tr>
<tr class="odd">
<td align="left">LGA</td>
<td align="right">7</td>
<td align="right">8927</td>
</tr>
<tr class="even">
<td align="left">LGA</td>
<td align="right">8</td>
<td align="right">8985</td>
</tr>
<tr class="odd">
<td align="left">LGA</td>
<td align="right">9</td>
<td align="right">9116</td>
</tr>
<tr class="even">
<td align="left">LGA</td>
<td align="right">10</td>
<td align="right">9642</td>
</tr>
<tr class="odd">
<td align="left">LGA</td>
<td align="right">11</td>
<td align="right">8851</td>
</tr>
<tr class="even">
<td align="left">LGA</td>
<td align="right">12</td>
<td align="right">9067</td>
</tr>
</tbody>
</table>
<pre class="r"><code>by_origin_month &lt;- flights %&gt;% 
  group_by(month, origin) %&gt;% 
  summarize(count = n())
kable(by_origin_month)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">month</th>
<th align="left">origin</th>
<th align="right">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">EWR</td>
<td align="right">9893</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="left">JFK</td>
<td align="right">9161</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="left">LGA</td>
<td align="right">7950</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">EWR</td>
<td align="right">9107</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="left">JFK</td>
<td align="right">8421</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">LGA</td>
<td align="right">7423</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">EWR</td>
<td align="right">10420</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="left">JFK</td>
<td align="right">9697</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">LGA</td>
<td align="right">8717</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">EWR</td>
<td align="right">10531</td>
</tr>
<tr class="odd">
<td align="right">4</td>
<td align="left">JFK</td>
<td align="right">9218</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">LGA</td>
<td align="right">8581</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">EWR</td>
<td align="right">10592</td>
</tr>
<tr class="even">
<td align="right">5</td>
<td align="left">JFK</td>
<td align="right">9397</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">LGA</td>
<td align="right">8807</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">EWR</td>
<td align="right">10175</td>
</tr>
<tr class="odd">
<td align="right">6</td>
<td align="left">JFK</td>
<td align="right">9472</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">LGA</td>
<td align="right">8596</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="left">EWR</td>
<td align="right">10475</td>
</tr>
<tr class="even">
<td align="right">7</td>
<td align="left">JFK</td>
<td align="right">10023</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="left">LGA</td>
<td align="right">8927</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">EWR</td>
<td align="right">10359</td>
</tr>
<tr class="odd">
<td align="right">8</td>
<td align="left">JFK</td>
<td align="right">9983</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">LGA</td>
<td align="right">8985</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="left">EWR</td>
<td align="right">9550</td>
</tr>
<tr class="even">
<td align="right">9</td>
<td align="left">JFK</td>
<td align="right">8908</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="left">LGA</td>
<td align="right">9116</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">EWR</td>
<td align="right">10104</td>
</tr>
<tr class="odd">
<td align="right">10</td>
<td align="left">JFK</td>
<td align="right">9143</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">LGA</td>
<td align="right">9642</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="left">EWR</td>
<td align="right">9707</td>
</tr>
<tr class="even">
<td align="right">11</td>
<td align="left">JFK</td>
<td align="right">8710</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="left">LGA</td>
<td align="right">8851</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="left">EWR</td>
<td align="right">9922</td>
</tr>
<tr class="odd">
<td align="right">12</td>
<td align="left">JFK</td>
<td align="right">9146</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="left">LGA</td>
<td align="right">9067</td>
</tr>
</tbody>
</table>
<p>This grouping orders first by <code>month</code> and then by <code>origin</code> whereas the previous grouping orders by <code>origin</code> and then by <code>month</code>. This is a simple way to sort data but you should be careful to make sure you are grouping in the appropriate order.</p>
</div>
<div id="lc5.9" class="section level2">
<h2>LC5.9</h2>
<p>How does the <code>filter</code> operation differ from a <code>group_by</code> followed by a <code>summarize</code>?</p>
<p><strong>Discussion</strong>:</p>
<p><code>filter</code> only reduces the total number of rows in the original data frame to only choose those that match a given set of conditions. <code>group_by</code> with <code>summarize</code> creates an aggregated data frame that fundamentally is of a different size with different variables than the original data frame.</p>
</div>
<div id="lc5.10" class="section level2">
<h2>LC5.10</h2>
<p>What do positive values of the <code>gain</code> variable in <code>flights</code> correspond to? What about negative values? And what about a zero value?</p>
<p><strong>Discussion</strong>:</p>
<p>Observing how <code>gain</code> was defined will give us a better understanding:</p>
<pre class="r"><code>flights &lt;- flights %&gt;% 
  mutate(gain = arr_delay - dep_delay)</code></pre>
<p>We can see that this value will be positive when <code>arr_delay</code> is larger than <code>dep_delay</code> and negative when <code>dep_delay</code> is larger than <code>arr_delay</code>. A zero value corresponds to no gain on the flight. This means that the pilot was not able to make up any time on the flight. A positive gain means that the pilot was NOT able to make up time during the flight since the arrival delay is more than the departure delay. A negative gain means that the pilot was able to make up time during the flight.</p>
</div>
<div id="lc5.11" class="section level2">
<h2>LC5.11</h2>
<p>Could we create the <code>dep_delay</code> and <code>arr_delay</code> columns by simply subtracting <code>dep_time</code> from <code>sched_dep_time</code> and similarly for arrivals? Try the code out and explain any differences between the result and what actually appears in <code>flights</code>.</p>
<p><strong>Discussion</strong>:</p>
<p>We use the <code>mutate()</code> function to create new variables. We will also <code>select</code> only the two newly created variables and <code>dep_delay</code> and <code>arr_delay</code>. Lastly, we include <code>dep_time</code> and <code>sched_dep_time</code> to see if the subtractions are correct and display the first 15 rows.</p>
<pre class="r"><code>flights_new &lt;- flights %&gt;%
  mutate(my_dep_delay = dep_time - sched_dep_time,
         my_arr_delay = arr_time - sched_arr_time) %&gt;% 
  select(dep_time, sched_dep_time, my_dep_delay, dep_delay, my_arr_delay, arr_delay)
head(flights_new, 15)</code></pre>
<pre><code>## # A tibble: 15 × 6
##    dep_time sched_dep_time my_dep_delay dep_delay my_arr_delay arr_delay
##       &lt;int&gt;          &lt;int&gt;        &lt;int&gt;     &lt;dbl&gt;        &lt;int&gt;     &lt;dbl&gt;
## 1       517            515            2         2           11        11
## 2       533            529            4         4           20        20
## 3       542            540            2         2           73        33
## 4       544            545           -1        -1          -18       -18
## 5       554            600          -46        -6          -25       -25
## 6       554            558           -4        -4           12        12
## 7       555            600          -45        -5           59        19
## 8       557            600          -43        -3          -14       -14
## 9       557            600          -43        -3           -8        -8
## 10      558            600          -42        -2            8         8
## 11      558            600          -42        -2           -2        -2
## 12      558            600          -42        -2           -3        -3
## 13      558            600          -42        -2            7         7
## 14      558            600          -42        -2          -14       -14
## 15      559            600          -41        -1           31        31</code></pre>
<p>We see that the first four rows look OK, but then some problems occur. <code>my_dep_delay</code> gives a value of <code>-46</code> when the true <code>dep_delay</code> is <code>-6</code>. You can see that this is due shifting to a new hour. Since <code>600 - 554 = -46</code>, it isn’t as simple as just subtracting the two rows to get the delay. You also need to account for their only being 60 minutes in an hour not 100.</p>
</div>
<div id="lc5.12" class="section level2">
<h2>LC5.12</h2>
<p>What can we say about the distribution of <code>gain</code>? Describe it in a few sentences using the plot and the <code>gain_summary</code> data frame values.</p>
<p><strong>Discussion</strong>:</p>
<p>Here are the plot and summary values:</p>
<pre class="r"><code>library(ggplot2)
ggplot(data = flights, mapping = aes(x = gain)) +
  geom_histogram(color = &quot;white&quot;, bins = 20)</code></pre>
<p><img src="figures/unnamed-chunk-20-1.png" width="672" /></p>
<pre class="r"><code>gain_summary &lt;- flights %&gt;% 
  summarize(
    min = min(gain, na.rm = TRUE),
    q1 = quantile(gain, 0.25, na.rm = TRUE),
    median = quantile(gain, 0.5, na.rm = TRUE),
    q3 = quantile(gain, 0.75, na.rm = TRUE),
    max = max(gain, na.rm = TRUE),
    mean = mean(gain, na.rm = TRUE),
    sd = sd(gain, na.rm = TRUE),
    missing = sum(is.na(gain))
  )
kable(gain_summary)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">min</th>
<th align="right">q1</th>
<th align="right">median</th>
<th align="right">q3</th>
<th align="right">max</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-109</td>
<td align="right">-17</td>
<td align="right">-7</td>
<td align="right">3</td>
<td align="right">196</td>
<td align="right">-5.659779</td>
<td align="right">18.04365</td>
<td align="right">9430</td>
</tr>
</tbody>
</table>
<p>We see from the plot that the distribution of <code>gain</code> is roughly symmetric, but with some skew to the right for some very long delays. The mean and median values are both negative which means that we can expect to arrive a few minutes earlier than expected if our flight departs late from NYC. The standard deviation value tells us that we can expect any given flight to be about 18 minutes away from the mean value of -5.66 minutes.</p>
</div>
<div id="lc5.13" class="section level2">
<h2>LC5.13</h2>
<p>Looking at Figure <a href="https://ismayc.github.io/moderndiver-book/5-manip.html#fig:reldiagram">5.7</a>, when joining <code>flights</code> and <code>weather</code> (or, in other words, matching the hourly weather values with each flight), why do we need to join by all of <code>year</code>, <code>month</code>, <code>day</code>, <code>hour</code>, and <code>origin</code>, and not just <code>hour</code>?</p>
<p><strong>Discussion</strong>:</p>
<p>The <code>hour</code> variable does not contain enough information for any given row in <code>flights</code> or <code>weather</code>. It just gives a single numeric value. Flights depart during an <code>hour</code> of a <code>day</code> in a <code>month</code> in a <code>year</code> from an <code>origin</code> airport. Weather is also recorded at these same variables.</p>
</div>
<div id="lc5.14" class="section level2">
<h2>LC5.14</h2>
<p>What surprises you about the top 10 destinations from NYC in 2013?</p>
<p><strong>Discussion</strong>:</p>
<p>This is referring to</p>
<pre class="r"><code>freq_dest &lt;- flights %&gt;% 
  group_by(dest) %&gt;%  
  summarize(num_flights = n()) %&gt;% 
  arrange(desc(num_flights))
freq_dest</code></pre>
<pre><code>## # A tibble: 105 × 2
##     dest num_flights
##    &lt;chr&gt;       &lt;int&gt;
## 1    ORD       17283
## 2    ATL       17215
## 3    LAX       16174
## 4    BOS       15508
## 5    MCO       14082
## 6    CLT       14064
## 7    SFO       13331
## 8    FLL       12055
## 9    MIA       11728
## 10   DCA        9705
## # ... with 95 more rows</code></pre>
<p>Answers will vary here. One thing that stands out is that the most flights go to Chicago (ORD) and Atlanta (ATL). These airports are not very close to New York City. Both of these airports are major hubs for airlines though which is likely driving them being at the top of the list as well as Los Angeles (LAX) and Boston (BOS).</p>
<hr />
</div>
</div>
<div id="ps10-key" class="section level1">
<h1>Problem Set 10</h1>
<p>Learning Checks <a href="https://ismayc.github.io/moderndiver-book/6-sim.html">LC6.1, LC6.3, LC6.9, LC6.11, LC6.13, LC6.15</a></p>
<div id="lc6.1" class="section level2">
<h2>LC6.1</h2>
<p>Explain in your own words how tasting soup relates to the concepts of sampling covered here.</p>
<p><strong>Discussion</strong>:</p>
<p>The entire pot of soup is the population. A sample would be a bowl of soup from that pot. Sampling is the process of selecting a bowl from the pot of soup. If the pot is stirred and the scoop is done at random, we can generalize to the entire pot of soup any characteristics we notice in the bowl of soup. If the pot is not stirred and there is bias in the selection of the sample (say if all carrots are chosen), we cannot generalize to the whole pot of soup but only to the sample selected.</p>
</div>
<div id="lc6.3" class="section level2">
<h2>LC6.3</h2>
<p>Why isn’t our population all bowls of soup? All bowls of Indian chicken soup?</p>
<p><strong>Discussion</strong>:</p>
<p>All bowls of Indian chicken soup (and thus all bowls of soup) may not have the same characteristics as this particular bowl of soup.</p>
</div>
<div id="lc6.9" class="section level2">
<h2>LC6.9</h2>
<p>Does this random sample of <code>height</code> represent the population height variable well? Explain why or why not in a couple of sentences.</p>
<p><strong>Discussion</strong>:</p>
<p>This question is referring to the following population plot and sample plot (with red fill):</p>
<pre class="r"><code>library(okcupiddata)
library(dplyr)
library(ggplot2)
library(mosaic)
profiles_subset &lt;- profiles %&gt;% filter(between(height, 55, 85))
ggplot(data = profiles_subset, mapping = aes(x = height)) +
  geom_histogram(bins = 20, color = &quot;white&quot;)</code></pre>
<p><img src="figures/unnamed-chunk-23-1.png" width="672" /></p>
<pre class="r"><code>set.seed(2017)
profiles_sample1 &lt;- profiles_subset %&gt;% 
  resample(size = 100, replace = FALSE)
ggplot(data = profiles_sample1, mapping = aes(x = height)) +
  geom_histogram(bins = 20, color = &quot;white&quot;, fill = &quot;red&quot;) +
  coord_cartesian(xlim = c(55, 85))</code></pre>
<p><img src="figures/unnamed-chunk-23-2.png" width="672" /></p>
<p>The overall shape of the sample is similar to the overall shape of the population. It also covers roughly the same values as the population covers in its histogram.</p>
</div>
<div id="lc6.11" class="section level2">
<h2>LC6.11</h2>
<p>Why is random sampling so important here to create a distribution of sample means that provide a range of plausible values for the population mean height?</p>
<p><strong>Discussion</strong>:</p>
<p>Without random sampling we have the potential for bias in our samples. If these samples are biased, when we calculate the mean of each sample we will have biased mean readings that will deviate far from what the actual population mean is. Random sampling ensures that bias is as close to eliminated as possible so we can be confident that our process would lead to a better estimation procedures of the population parameter.</p>
</div>
<div id="lc6.13" class="section level2">
<h2>LC6.13</h2>
<p>What is our observed statistic?</p>
<p><strong>Discussion</strong>:</p>
<p>This question refers to the “Lady Tasting Tea” experiment. Here it is the proportion of times the woman was able to correctly identify whether the tea or the milk was added first. The value here is 9/10 = 0.9.</p>
</div>
<div id="lc6.15" class="section level2">
<h2>LC6.15</h2>
<p>How could we test to see whether the person is just guessing or if they have some special talent of identifying milk before tea or vice-versa?</p>
<p><strong>Discussion</strong>:</p>
<p>We would begin by setting out 10 cups. We then use a coin to randomly assign to each cup whether we will add milk first or second. For our purposes, we will say that “heads” corresponds to milk first. We then ask the lady to taste each cup and identify whether or not milk was added first or second. It is important between each cup tasting for her to cleanse her palette so that each trial is independent of the others. If she correctly identifies a large proportion of the 10 cups correctly, we have reason to believe she may have a special talent.</p>
<p>This can be verified by performing many different coin flip simulations assuming a fair coin in sets of 10 and counting the number of heads. We can then see where the number we observed her getting correct falls on this distribution. If it falls out in the right tail, we can assume our initial assumption that she was just guessing may not be correct. If the observed number falls closer to the center of the distribution, we do not have evidence to go against or original assumption that she is just guessing.</p>
<hr />
</div>
</div>
<div id="ps11-key" class="section level1">
<h1>Problem Set 11</h1>
<p>Learning Checks <a href="https://ismayc.github.io/moderndiver-book/7-hypo.html">LC7.1 - LC7.5</a></p>
<div id="lc7.1" class="section level2">
<h2>LC7.1</h2>
<p>Could we make the same type of immediate conclusion that SFO had a statistically greater <code>air_time</code> if, say, its corresponding standard deviation was 200 minutes? What about 100 minutes? Explain.</p>
<p><strong>Discussion</strong>:</p>
<p>If SFO had a standard deviation of 100 minutes, the boxplots would likely still not overlap so we could have the same immediate conclusion. With a standard deviation of 200 minutes though, the data would be much more variable and likely there would be some overlap between the boxplot for SFO and BOS.</p>
</div>
<div id="lc7.2" class="section level2">
<h2>LC7.2</h2>
<p>Reproduce the table above about errors, but for a hypothesis test, instead of the one provided for a criminal trial.</p>
<p><strong>Discussion</strong>:</p>
<p>The original table for a criminal trial is below.</p>
<p><img src="https://ismayc.github.io/moderndiver-book/images/errors.png" alt="Drawing" style="width: 400px;"/></p>
<p>The corresponding table for a hypothesis test follows.</p>
<div class="figure">
<img src="http://vignette3.wikia.nocookie.net/whatilearned/images/4/45/Type_I_and_Type_II_Error_Table.jpg/revision/latest?cb=20110522022621" />

</div>
</div>
<div id="lc7.3" class="section level2">
<h2>LC7.3</h2>
<p>What is wrong about saying “The defendant is innocent.” based on the US system of criminal trials?</p>
<p><strong>Discussion</strong>:</p>
<p>You can never prove non-existence. You can only have evidence for or against a claim. Therefore, it is more appropriate and correct to say “The defendant is not guilty.” or better yet “There is not evidence to conclude that the defendant is guilty.”</p>
</div>
<div id="lc7.4" class="section level2">
<h2>LC7.4</h2>
<p>What is the purpose of hypothesis testing?</p>
<p><strong>Discussion</strong>:</p>
<p>Much like a criminal trial, hypothesis testing is used to see if the sample collected brings evidence forth against or in favor of the null hypothesis. If the sample and its observed statistic deviates far from what we expect to be true in the null hypothesis, we reject the original assumption in favor of the alternative hypothesis. The alternative hypothesis usually represents what the researchers are interested in testing or a claim that has been made.</p>
</div>
<div id="lc7.5" class="section level2">
<h2>LC7.5</h2>
<p>What are some flaws with hypothesis testing? How could we alleviate them?</p>
<p><strong>Discussion</strong>:</p>
<p>The biggest flaw with hypothesis testing is the fact that it only has two competing hypothesis and a choice must be made one way or the other based on the data. When we reject the null hypothesis, we often want to also know “But how far away might we expect the mean of one group to be from the other?” or similar questions. Much like a criminal trial, we aren’t necessarily sure of just “how guilty” a person may be and type I and type II errors can be made in criminal trials and hypothesis tests. Unfortunately, this is something built in to the process of both. The dichotomy is alleviated some by using confidence intervals to estimate the difference as is discussed in Chapter 8 of ModernDive.</p>
</div>
</div>



    </div>
  </article>

  

</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="../../index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://ismayc.github.io">Chester's homepage</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="../../images/hugo-logo.png" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    
    
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js"></script>
    
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/languages/r.min.js"></script>
    
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/languages/yaml.min.js"></script>
    
    <script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>
    
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre']
      }
    });
    </script>
    <script type="text/javascript"
      src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>
    
  </body>
</html>

